FROM node:18-alpine
WORKDIR /app


ARG PORT
ARG NODE_ENV
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_PORT
ARG DATABASE_SYNC
ARG ADMIN_USERNAME
ARG ADMIN_PASSWORD
ARG SECRET_KEY

ENV PORT $PORT
ENV NODE_ENV $NODE_ENV
ENV DATABASE_USER $DATABASE_USER
ENV DATABASE_PASSWORD $DATABASE_PASSWORD
ENV DATABASE_HOST $DATABASE_HOST
ENV DATABASE_NAME $DATABASE_NAME
ENV DATABASE_PORT $DATABASE_PORT
ENV DATABASE_SYNC $DATABASE_SYNC
ENV ADMIN_USERNAME $ADMIN_USERNAME
ENV ADMIN_PASSWORD $ADMIN_PASSWORD
ENV SECRET_KEY $SECRET_KEY

COPY ["package*.json", "tsconfig.build.json", "tsconfig.json", "./"]
RUN npm install
COPY . .
RUN npm run build

EXPOSE 80
CMD ["npm", "run", "start:dev"]